$(document).ready(function(){
   $('.true-slider').slick({
      arrows:true,
      dots:false,
      //slidesToShow:1;
      //slidesToScroll:2;
      speed:300,
      easing:'ease',
      infinite:false,
   });
});