$(document).ready(function(){
   $('.true-slider').slick({
      arrows:true,
      dots:false,
      //slidesToShow:1;
      //slidesToScroll:2;
      speed:1000,
      easing:'ease',
      infinite:true,
      autoplay:true,
      autoplaySpeed:4000,
   });
});